[package]
name = "test-app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "test_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri-plugin-shell = "2"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-os = "2"
tauri-plugin-http = "2"
tauri-plugin-localhost = "2"
tauri-plugin-opener = "2"
tauri-plugin-store = "2"
tauri-plugin-deep-link = { git = "https://github.com/FabianLars/tauri-plugin-deep-link", branch = "main" }
tauri-plugin-window-state = "2"
#
hoppscotch-relay = { path = "../../../../hoppscotch/packages/hoppscotch-relay" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = "2.5.2"
thiserror = "2.0.12"
dashmap = "6.1.0"
log = "0.4.27"
hex_color = "3.0.0"
windows = "0.61.3"
windows-sys = "0.60.2"
winver = "1.0.0"
tokio = { version = "1", features = ["macros", "rt"] }
tokio-util = "0.7.15"

[dev-dependencies]
# unresolved import `tauri::test`
tauri = { version = "2", features = ["test"] }
#
env_logger = "0.11.5"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.25.0"
objc = "0.2.7"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.52.0", features = [
  "Win32_Graphics_Dwm",
  "Win32_Foundation",
  "Win32_UI_Controls",
] }
winver = "1"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]